version: "3.9"

networks:
  dev:
    driver: bridge

services:
  flowapp:
    stdin_open: true
    tty: true
    container_name: flowapp_flowapp_1    
    build: .    
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:5000
      - ErrorsStoreDatabase__ConnectionString=mongodb://mongodb:27017
      - DefaultConnection__ConnectionStrings=Server=postgres;Database=FlowApp;Port=5432;User Id=postgres;Password=123456;
    depends_on:
      - postgres
      - mongodb
    networks:
      - dev
  postgres:
    container_name: flowapp_postgres_1
    image: postgres:14-alpine
    ports:
      - "5432:5432"    
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=FlowApp       
    networks:
      - dev   
  mongodb:
    container_name: flowapp_mongodb_1
    image: mongo:7.0.10-rc0-jammy
    ports:
      - "27017:27017"
    networks:
      - dev  
